# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec16fdafbe4c514aca01a0fe140496b6c861dc89588543ed5fb7ba627fb5b64f7af9c1536e0b5db109557af3c411f6a02efb847a988f4ad324a106702a0756fc

test:
  secret_key_base: c69d9cd1f3f8e68ce31e4055e99c0de2230a836e3fc0c94c761df0a730b9bcb1793338c805b5a10a469f3ed3175f3ccfb7ece43a676c5b74ef318f41ebf50798

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
